### ISSUE TITLE
Ask about trainning model

### ISSUE THREAD

**Issue by mscb402** [Hxyz-123/Font-diff#5]
I used 500 sets of fonts, trained for 120 hours, and iterated 950,000 times (the last 400,000 were pre-train). However, the obtained model is completely different from what was expected. Firstly, there is a lot of noise in the obtained samples, which cannot be removed from the beginning to the end. Secondly, it completely cannot learn the correct way of writing Chinese characters, and all of them are wrong strokes. Helplessly, I have to give up and consult how you trained this model? And does this model really work?
And below is the same character "陈"
![928000_00000](https://github.com/Hxyz-123/Font-diff/assets/11229089/7d371020-6c40-42cd-b6ff-1c5d010353f6)
![934000_00000](https://github.com/Hxyz-123/Font-diff/assets/11229089/049856a6-e727-45b0-8542-054b87287ac7)

**Comment by chenjingcheng** [comment]
Based on my testing, I found that when using the same reference image and inputting the same Chinese character, the output image generated each time is different. If only one image is used to obtain the entire set of font styles, I personally believe that this is not feasible. If 500-1000 typical Chinese characters are used as input to generate a set of fonts, it would be more feasible. The so-called "few characters" mentioned in the paper are mostly gimmicks and have almost no practical value.

**Comment by chenjingcheng** [comment]
> 

Hello, thank you for your response. Currently, I have selected 470 fonts, although there may be a few fonts that are missing certain characters. Most of them include the character set you recommended. Additionally, I have a question: Do you use only one image for inference, or do you use multiple images of the same font for inference? I believe that using just one image is difficult to learn the style and skeletal structure of the characters. Thank you.

**Comment by mscb402** [comment]
> > I used 500 sets of fonts, trained for 120 hours, and iterated 950,000 times (the last 400,000 were pre-train). However, the obtained model is completely different from what was expected. Firstly, there is a lot of noise in the obtained samples, which cannot be removed from the beginning to the end. Secondly, it completely cannot learn the correct way of writing Chinese characters, and all of them are wrong strokes. Helplessly, I have to give up and consult how you trained this model? And does this model really work? And below is the same character "陈" ![928000_00000](https://user-images.githubusercontent.com/11229089/237094316-7d371020-6c40-42cd-b6ff-1c5d010353f6.png) ![934000_00000](https://user-images.githubusercontent.com/11229089/237094335-049856a6-e727-45b0-8542-054b87287ac7.png)
> 
> Hello, can you tell me your training settings and how you create your own dataset?

Here is my `train.cfg`
```yaml
data_dir: "/datasets"
chara_nums: 6625
diffusion_steps: 1500
noise_schedule: "linear"
image_size: 128
num_channels: 128
num_res_blocks: 3
lr: 0.0001
batch_size: 10
log_interval: 100
save_interval: 2000
train_step: 600000
attention_resolutions: "40, 20, 10"
sty_encoder_path: "./pretrained_models/chinese_styenc.ckpt"
resume_checkpoint: "./trained_models/model912000.pt"
model_save_dir: "./trained_models"
stroke_path: "./chinese_stroke.txt"
classifier_free: True
total_train_step: 1000000
```
